name: Build Windows EXE

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Change directory
        run: cd src

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Build EXE
        run: |
          pyinstaller --noconsole --onefile --icon=img/fire.ico --add-data "img;img" --name="Firelink" main.py

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Firelink-Windows
          path: dist/Firelink.exe
